Imputing misding values by Random Forest Imputer

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error,root_mean_squared_error,mean_absolute_error, mean_absolute_percentage_error,r2_score

data = sns.load_dataset('titanic')
data.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [67]:
data.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [68]:
data.drop('deck',axis=1,inplace=True)
data.head()

   survived  pclass     sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    male  22.0  ...        True  Southampton     no  False
1         1       1  female  38.0  ...       False    Cherbourg    yes  False
2         1       3  female  26.0  ...       False  Southampton    yes   True
3         1       1  female  35.0  ...       False  Southampton    yes  False
4         0       3    male  35.0  ...        True  Southampton     no   True

[5 rows x 14 columns]

In [69]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    str
 12  alive        891 non-null    str
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 79.4 KB

In [70]:
data.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='str')

In [71]:
# Encode the data columns as required (change data type)
columns_to_decode = ['sex','age','embarked', 'class', 'who','embark_town', 'alive']

#dictionary to store decode-values
decode_values = {}

for col in columns_to_decode:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    decode_values[col] = le
data.head()

   survived  pclass  sex  age  ...  adult_male  embark_town  alive  alone
0         0       3    1   28  ...        True            2      0  False
1         1       1    0   51  ...       False            0      1  False
2         1       3    0   34  ...       False            2      1   True
3         1       1    0   47  ...       False            2      1  False
4         0       3    1   47  ...        True            2      0   True

[5 rows x 14 columns]

In [72]:
#missing values  into two parts (missing and non-missing)
data_with_missing = data[data['age'].isna()] 
data_without_missing = data.dropna()

In [73]:
X = data_without_missing.drop(['age'],axis=1)
y = data_without_missing['age']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

model = RandomForestRegressor(n_estimators = 100, random_state=42)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)
print("r2_score: ",r2_score(y_test,y_pred))
print("mean_absolute_error: ",mean_absolute_error(y_test,y_pred))
print("mean_absolute_percentage_error: ",mean_absolute_percentage_error(y_test,y_pred))
print("mean_squared_error: ",np.sqrt(mean_squared_error(y_test,y_pred)))

r2_score:  0.292085152625453
mean_absolute_error:  16.52473955313221
mean_absolute_percentage_error:  0.4168326728391639
mean_squared_error:  21.456757850271504

In [74]:
print(data_without_missing)

     survived  pclass  sex  age  ...  adult_male  embark_town  alive  alone
0           0       3    1   28  ...        True            2      0  False
1           1       1    0   51  ...       False            0      1  False
2           1       3    0   34  ...       False            2      1   True
3           1       1    0   47  ...       False            2      1  False
4           0       3    1   47  ...        True            2      0   True
..        ...     ...  ...  ...  ...         ...          ...    ...    ...
886         0       2    1   35  ...        True            2      0   True
887         1       1    0   24  ...       False            2      1   True
888         0       3    0   88  ...       False            2      0  False
889         1       1    1   34  ...        True            0      1   True
890         0       3    1   42  ...        True            1      0   True

[891 rows x 14 columns]

In [80]:
y_pred = model.predict(data_with_missing.drop(['age'], axis=1))

In [81]:
print(y_pred)

[48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076 48.49367076
 48.49367076 48.49367076 48.49367076]

In [82]:
# remove warnings
import warnings
warnings.filterwarnings('ignore')

#replace with predicted values
data_with_missing['age'] = y_pred
data_with_missing.isnull().sum().sort_values(ascending=False)

survived       891
pclass         891
sex            891
sibsp          891
parch          891
fare           891
adult_male     891
embarked       891
class          891
who            891
alive          891
embark_town    891
alone          891
age              0
dtype: int64